const { contextBridge, ipcRenderer } = require('electron');

const nativeApi = {
    expand_overlay: () => ipcRenderer.invoke('trace:expand-overlay'),
    show_orb: () => ipcRenderer.invoke('trace:show-orb'),
    toggle_compact: () => ipcRenderer.invoke('trace:toggle-compact'),
    toggle_wake: () => ipcRenderer.invoke('trace:toggle-wake'),
    toggle_compact_visibility: () => ipcRenderer.invoke('trace:toggle-compact-visibility'),
    wake_compact: () => ipcRenderer.invoke('trace:wake-compact'),
    sleep_assistant: () => ipcRenderer.invoke('trace:sleep-assistant'),
    collapse_overlay: () => ipcRenderer.invoke('trace:collapse-overlay'),
    show_dashboard: () => ipcRenderer.invoke('trace:show-dashboard'),
    enter_compact: () => ipcRenderer.invoke('trace:enter-compact'),
    capture_screen: () => ipcRenderer.invoke('trace:capture-screen'),
    generate_diagnostic: () => ipcRenderer.invoke('trace:generate-diagnostic'),
    calibrate_claps: () => ipcRenderer.invoke('trace:calibrate-claps'),
    reset_claps: () => ipcRenderer.invoke('trace:reset-claps'),
    start_listening: () => ipcRenderer.invoke('trace:start-listening'),
    set_ambient: enabled => ipcRenderer.invoke('trace:set-ambient', enabled),
    get_shortcut: () => ipcRenderer.invoke('trace:get-shortcut'),
    runtime_state: () => ipcRenderer.invoke('trace:runtime-state'),
    get_startup: () => ipcRenderer.invoke('trace:get-startup'),
    set_startup: enabled => ipcRenderer.invoke('trace:set-startup', enabled),
    select_files: () => ipcRenderer.invoke('trace:select-files'),
    save_document: (data) => ipcRenderer.invoke('trace:save-document', data),
    select_app: () => ipcRenderer.invoke('trace:select-app'),
    list_apps: () => ipcRenderer.invoke('trace:list-apps'),
    detect_apps: () => ipcRenderer.invoke('trace:detect-apps'),
    set_app_authorized: (app, authorized) => ipcRenderer.invoke('trace:set-app-authorized', app, authorized),
    launch_app: (query) => ipcRenderer.invoke('trace:launch-app', query),
    list_routines: () => ipcRenderer.invoke('trace:list-routines'),
    save_routine: (data) => ipcRenderer.invoke('trace:save-routine', data),
    delete_routine: (name) => ipcRenderer.invoke('trace:delete-routine', name),
    run_routine: (query) => ipcRenderer.invoke('trace:run-routine', query),
    report_mic: (level, status) => ipcRenderer.invoke('trace:mic-level', { level, status }),
    on_mic: callback => ipcRenderer.on('trace:mic-level', (_event, data) => callback(data)),
    broadcast: data => ipcRenderer.invoke('trace:broadcast', data),
    on_event: callback => ipcRenderer.on('trace:event', (_event, data) => callback(data)),
    on_overlay_mode: callback => ipcRenderer.on('trace:overlay-mode', (_event, mode) => callback(mode)),
    on_native_wake: callback => ipcRenderer.on('trace:native-wake', (_event, data) => callback(data)),
    on_wake_status: callback => ipcRenderer.on('trace:wake-status', (_event, data) => callback(data)),
    on_clap_calibration: callback => ipcRenderer.on('trace:clap-calibration', (_event, action) => callback(action)),
    on_start_listening: callback => ipcRenderer.on('trace:start-listening', callback),
    on_ambient_control: callback => ipcRenderer.on('trace:ambient-control', (_event, enabled) => callback(enabled)),
    on_global_command: callback => ipcRenderer.on('trace:global-command', callback)
};

contextBridge.exposeInMainWorld('noaNative', nativeApi);
// Temporary compatibility surface while old renderer code and persisted data are migrated.
contextBridge.exposeInMainWorld('traceNative', nativeApi);
